// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web.Models.EF;

#nullable disable

namespace Web.Migrations
{
    [DbContext(typeof(FoodContext))]
    [Migration("20260712160503_s10")]
    partial class s10
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Database.Models.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Keyword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Picture")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Article");
                });

            modelBuilder.Entity("Core.Database.Models.Authorized", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("RoleId");

                    b.ToTable("Authorized");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a5c5295c-312c-4c44-8135-5c0e9241702a"),
                            GroupId = new Guid("eb6b4076-ae9a-4d83-9522-f71760bf27b4"),
                            RoleId = new Guid("b643e139-b6bf-41d7-a251-ad3bd2ae5574")
                        });
                });

            modelBuilder.Entity("Core.Database.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f3dadf45-7db1-4ec9-89bc-f29eed14d099"),
                            CreatedBy = new Guid("98d64f50-d8ce-4c84-90cc-4131af413f2a"),
                            CreatedOn = new DateTime(2026, 7, 12, 23, 4, 58, 285, DateTimeKind.Local).AddTicks(6224),
                            Name = "Root"
                        },
                        new
                        {
                            Id = new Guid("4d84c1f5-3daa-439a-93cd-8b60dc29192d"),
                            CreatedBy = new Guid("98d64f50-d8ce-4c84-90cc-4131af413f2a"),
                            CreatedOn = new DateTime(2026, 7, 12, 23, 4, 58, 285, DateTimeKind.Local).AddTicks(6294),
                            Name = "Authorized",
                            ParentId = new Guid("f3dadf45-7db1-4ec9-89bc-f29eed14d099")
                        },
                        new
                        {
                            Id = new Guid("fe7f810c-72b9-44cb-ab4b-3faf28cdc443"),
                            CreatedBy = new Guid("98d64f50-d8ce-4c84-90cc-4131af413f2a"),
                            CreatedOn = new DateTime(2026, 7, 12, 23, 4, 58, 285, DateTimeKind.Local).AddTicks(6299),
                            Name = "Nhóm quyền",
                            ParentId = new Guid("4d84c1f5-3daa-439a-93cd-8b60dc29192d")
                        },
                        new
                        {
                            Id = new Guid("348b75cd-56a7-4094-97f1-284ab85c3ab9"),
                            CreatedBy = new Guid("98d64f50-d8ce-4c84-90cc-4131af413f2a"),
                            CreatedOn = new DateTime(2026, 7, 12, 23, 4, 58, 285, DateTimeKind.Local).AddTicks(6303),
                            Name = "Article",
                            ParentId = new Guid("f3dadf45-7db1-4ec9-89bc-f29eed14d099")
                        },
                        new
                        {
                            Id = new Guid("d4f86670-a689-4cc2-90df-0e89ba79276d"),
                            CreatedBy = new Guid("98d64f50-d8ce-4c84-90cc-4131af413f2a"),
                            CreatedOn = new DateTime(2026, 7, 12, 23, 4, 58, 285, DateTimeKind.Local).AddTicks(6307),
                            Name = "Product",
                            ParentId = new Guid("f3dadf45-7db1-4ec9-89bc-f29eed14d099")
                        });
                });

            modelBuilder.Entity("Core.Database.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoginName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Core.Database.Models.Details", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Amount")
                        .HasColumnType("int");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("Details");
                });

            modelBuilder.Entity("Core.Database.Models.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Group");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eb6b4076-ae9a-4d83-9522-f71760bf27b4"),
                            Name = "Quản trị viên"
                        });
                });

            modelBuilder.Entity("Core.Database.Models.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoginName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Picture")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Member");

                    b.HasData(
                        new
                        {
                            Id = new Guid("98d64f50-d8ce-4c84-90cc-4131af413f2a"),
                            CreatedOn = new DateTime(2026, 7, 12, 23, 4, 58, 285, DateTimeKind.Local).AddTicks(6147),
                            Email = "mibn.24th@sv.dla.edu.vn",
                            GroupId = new Guid("eb6b4076-ae9a-4d83-9522-f71760bf27b4"),
                            LoginName = "bui.mi",
                            Name = "Bùi Ngọc Thảo Mi",
                            Password = "c4ca4238a0b923820dcc509a6f75849b",
                            Picture = "/img/users/thaomi.jpg"
                        });
                });

            modelBuilder.Entity("Core.Database.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Core.Database.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Intro")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("IsComming")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Picture")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Core.Database.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b643e139-b6bf-41d7-a251-ad3bd2ae5574"),
                            CategoryId = new Guid("fe7f810c-72b9-44cb-ab4b-3faf28cdc443"),
                            Code = "view-groups",
                            Name = "Xem danh sách"
                        },
                        new
                        {
                            Id = new Guid("ce1c61ac-219e-40d3-b780-9732052b4375"),
                            CategoryId = new Guid("fe7f810c-72b9-44cb-ab4b-3faf28cdc443"),
                            Code = "edit-group",
                            Name = "Cập nhật"
                        },
                        new
                        {
                            Id = new Guid("6157c9c4-23b3-47e3-bae7-38388367a439"),
                            CategoryId = new Guid("fe7f810c-72b9-44cb-ab4b-3faf28cdc443"),
                            Code = "save-group",
                            Name = "Lưu"
                        },
                        new
                        {
                            Id = new Guid("4fe07974-7ad0-49e4-8485-8a0b8dfac350"),
                            CategoryId = new Guid("fe7f810c-72b9-44cb-ab4b-3faf28cdc443"),
                            Code = "delete-group",
                            Name = "Xóa"
                        });
                });

            modelBuilder.Entity("Core.Database.Models.Authorized", b =>
                {
                    b.HasOne("Core.Database.Models.Group", "Group")
                        .WithMany("Authorizeds")
                        .HasForeignKey("GroupId");

                    b.HasOne("Core.Database.Models.Role", "Role")
                        .WithMany("Authorizeds")
                        .HasForeignKey("RoleId");

                    b.Navigation("Group");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Core.Database.Models.Category", b =>
                {
                    b.HasOne("Core.Database.Models.Category", "Parent")
                        .WithMany("ChildCategories")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Core.Database.Models.Details", b =>
                {
                    b.HasOne("Core.Database.Models.Order", "Order")
                        .WithMany("Details")
                        .HasForeignKey("OrderId");

                    b.HasOne("Core.Database.Models.Product", "Product")
                        .WithMany("Details")
                        .HasForeignKey("ProductId");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Core.Database.Models.Member", b =>
                {
                    b.HasOne("Core.Database.Models.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Core.Database.Models.Order", b =>
                {
                    b.HasOne("Core.Database.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Core.Database.Models.Product", b =>
                {
                    b.HasOne("Core.Database.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Core.Database.Models.Role", b =>
                {
                    b.HasOne("Core.Database.Models.Category", "Category")
                        .WithMany("Roles")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Core.Database.Models.Category", b =>
                {
                    b.Navigation("ChildCategories");

                    b.Navigation("Products");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Core.Database.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Core.Database.Models.Group", b =>
                {
                    b.Navigation("Authorizeds");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Core.Database.Models.Order", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("Core.Database.Models.Product", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("Core.Database.Models.Role", b =>
                {
                    b.Navigation("Authorizeds");
                });
#pragma warning restore 612, 618
        }
    }
}
